# Generated by Django 5.1.1 on 2024-10-14 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SECID', models.CharField(max_length=20, unique=True)),
                ('SHORTNAME', models.CharField(max_length=100)),
                ('BOARDID', models.CharField(max_length=10)),
                ('MARKET', models.CharField(max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
