# Generated by Django 5.1.1 on 2024-10-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('current_price', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Security',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('current_price', models.FloatField(default=0)),
            ],
        ),
    ]
