# Generated by Django 5.1.1 on 2024-11-12 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('price', models.FloatField()),
                ('security', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainview.security')),
            ],
        ),
    ]
